# Generated by Django 3.2.19 on 2023-06-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_appointments', to='users.vaccinator'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admindashboard.slot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_appointments', to='admindashboard.location'),
        ),
    ]
