# Generated by Django 3.2.19 on 2023-06-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
