# Generated by Django 3.2.19 on 2023-06-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_slot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='regular_working_slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_slots', to='admindashboard.location'),
        ),
    ]
