# Generated by Django 3.2.19 on 2023-06-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_auto_20230622_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dose_booked_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_booked_appointments', to='admindashboard.dose'),
        ),
    ]
