# Generated by Django 3.2.19 on 2023-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0007_appointment_medicine_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='min_days_after_prev_dose',
            field=models.IntegerField(default=90),
        ),
    ]
